# Generated by Django 5.1.2 on 2025-01-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tro_hay_ho_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='administrativeregion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='district',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='following',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='province',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='typelocation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
