# Generated by Django 5.1.2 on 2025-01-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tro_hay_ho_app', '0002_administrativeregion_administrativeunit_province_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrativeregion',
            table='administrative_regions',
        ),
        migrations.AlterModelTable(
            name='administrativeunit',
            table='administrative_units',
        ),
        migrations.AlterModelTable(
            name='district',
            table='districts',
        ),
        migrations.AlterModelTable(
            name='province',
            table='provinces',
        ),
        migrations.AlterModelTable(
            name='ward',
            table='wards',
        ),
    ]
