# Generated by Django 5.1.2 on 2025-01-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tro_hay_ho_app', '0003_post_is_show_alter_comment_replied_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.ForeignKey(null=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='post', to='tro_hay_ho_app.address'),
        ),
    ]
