# Generated by Django 5.1.2 on 2025-01-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tro_hay_ho_app', '0004_alter_post_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('renter', 'Renter'), ('admin', 'Admin')], default='user', max_length=15),
        ),
    ]
