# Generated by Django 5.1.2 on 2025-01-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tro_hay_ho_app', '0004_alter_address_district_alter_address_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(blank=True, db_column='province_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to='tro_hay_ho_app.province'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='district',
            field=models.ForeignKey(blank=True, db_column='district_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='tro_hay_ho_app.district'),
        ),
    ]
