# Generated by Django 5.1.2 on 2025-01-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tro_hay_ho_app', '0004_favoritepost'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favoritepost',
            table='favourite_post',
        ),
    ]
