# Generated by Django 5.1.2 on 2025-02-04 03:55

import cloudinary.models
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tro_hay_ho_app', '0008_user_unique_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuTro',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chu_tros', related_query_name='chu_tro', to='tro_hay_ho_app.address')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('tro_hay_ho_app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('image_tro', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image_tro')),
                ('chu_tro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_tro', to='tro_hay_ho_app.chutro')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
