# Generated by Django 5.1.2 on 2025-02-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tro_hay_ho_app', '0009_chutro_troimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chutro',
            options={},
        ),
        migrations.AlterModelTable(
            name='chutro',
            table='chu_tro',
        ),
    ]
